BEGIN;

DROP TABLE IF EXISTS mbtiInfo CASCADE;

CREATE TABLE mbtiInfo (
      id SERIAL PRIMARY KEY,
      mbtiType VARCHAR(6) NOT NULL,
      about VARCHAR(800) NOT NULL,
      relationshipDescrip1 VARCHAR(800) NOT NULL,
      relationshipDescript2 VARCHAR(800) NOT NULL,
      moreInfoLink TEXT NOT NULL
);

INSERT INTO
      mbtiInfo (mbtiType, about, relationshipDescrip1, relationshipDescript2, moreInfoLink)
VALUES
      ('ISFJ', 'The Defender personality type is quite unique, as many of their qualities defy the definition of their individual traits. Though sensitive, Defenders have excellent analytical abilities; though reserved, they have well-developed people skills and robust social relationships; and though they are generally a conservative type, Defenders are often receptive to change and new ideas. As with so many things, people with the Defender personality type are more than the sum of their parts, and it is the way they use these strengths that defines who they are.', 'When it comes to romantic relationships, Defenders’ kindness grows into a joy that is only found in taking care of their family and home, in being there for emotional and practical support whenever it’s needed. Home is where the heart is for people with the Defender personality type, and in no other area of their lives do they strive with such dedication to create the harmony and beauty they wish to see in the world.', 'The trouble is, these are the benefits of an established long-term relationship, and Defenders’ unbearable shyness means it can take a long time to reach this point. Defenders are most attractive when they are simply being themselves in a comfortable environment such as work, where their natural flow shows this kindness and dedication. Relationships built on established familiarity are a warm prospect for Defenders – they take dating seriously and only enter into relationships that have a real chance of lasting a lifetime.', 'https://www.16personalities.com/isfj-personality'),
      ('ENFP','The Campaigner personality is a true free spirit. They are often the life of the party, but unlike types in the Explorer Role group, Campaigners are less interested in the sheer excitement and pleasure of the moment than they are in enjoying the social and emotional connections they make with others. Charming, independent, energetic and compassionate, the 7% of the population that they comprise can certainly be felt in any crowd.', 'When it comes to relationships, there’s hardly anyone around who is more excited than Campaigners to share with their partners the bounty of ideas and eye-opening experiences that life has to offer. For people with the Campaigner personality type, relationships are a joyous process of mutual exploration and imagination, a chance to connect with another soul. Campaigners take their relationships seriously, and are known for their uninhibited and unshakeable devotion to the people to whom they’ve committed their hearts.', 'In the dating phase, if Campaigners can be said to tolerate such a formal process to begin with, they will show these qualities by showering their new flames with affection, and will do everything they can to build a strong relationship by demonstrating their devotion and reliability by whatever means available.', 'https://www.16personalities.com/ENFP-personality'),
      ('ENTP', 'No one loves the process of mental sparring more than the Debater personality type, as it gives them a chance to exercise their effortlessly quick wit, broad accumulated knowledge base, and capacity for connecting disparate ideas to prove their points. Debaters are the ultimate devil’s advocate, thriving on the process of shredding arguments and beliefs and letting the ribbons drift in the wind for all to see. They don’t always do this because they are trying to achieve some deeper purpose or strategic goal, though. Sometimes it’s for the simple reason that it’s fun.', 'If there’s one thing Debaters are good at, it’s coming up with a never-ending stream of innovations and ideas to keep things moving forward, and this is evident in their romantic relationships as well. For people with the Debater personality type growth is key, and even before they’ve found a dating partner, they imagine all the ways that they can experience new things together, to grow in tandem. This can be an overwhelming process if their partner doesn’t match up, but when Debaters find someone who shares their love of intellectual exploration, watch out.', 'From the earliest dates, Debaters test their partners’ limits for this kind of potential, pushing boundaries and traditions, looking for open-mindedness and spontaneity. Dating Debater personalities is hardly a boring experience, and they make use of their enthusiasm and creativity by delighting and surprising their partners with new ideas and experiences.', 'https://www.16personalities.com/entp-personality');

END;